# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_reonu_hero_mode"

# Version of this mod.
version = "1.0.4"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Hero Mode"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
Adds the following options: 
* A customizable damage multiplier (2x by default)
* An option to disable all recovery heart drops (on by default)
* An option to disable recovery fairies drops (off by default)
* An option to lose all rupees on death (off by default)

The default settings mimic the Hero mode in other Zelda games."""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Ok but what if it was like Dark Souls though?"

# Authors of this mod.
authors = [ "Reonu" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
# Example dependency:
#    "modname:1.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_hero_mode"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = ["thumb.dds"]

[[manifest.config_options]]
id = "disable_recovery_hearts"
name = "Disable Recovery Hearts"
description = "Prevent recovery hearts from spawning. Default is yes."
type = "Enum"
options = [ "Yes", "No" ]
default = "Yes"

[[manifest.config_options]]
id = "disable_fairies"
name = "Disable Fairies"
description = "Prevent fairies from spawning. Default is no."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "lose_rupees_on_death"
name = "Lose Rupees on Death"
description = "If enabled, you will lose all your rupees upon dying. Default is no."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "one_hit_ko"
name = "One Hit KO"
description = "Okay NOW it is like Dark Souls"
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "damage_multiplier"
name = "Damage Multiplier"
description = "How much damage should be multiplied by. Default is 2."
type = "Number"
min = 1
max = 100
step = 1
precision = 1
percent = false
default = 2

#[[manifest.config_options]]
#id = "string_option"
#name = "String Option"
#description = "Test string config option."
#type = "String"
#default = "Lorem Ipsum"
